### ISSUE TITLE
Is it working now?

### ISSUE THREAD

**Issue by hsluoyz** [will7200/casbin-idea-plugin#1]
Great to see such a project! Is it working now?

**Comment by will7200** [comment]
@hsluoyz Almost. Jetbrains request a small change. I will resubmit and it should be publicly available!

**Comment by hsluoyz** [comment]
Looking forward to it!

**Comment by will7200** [comment]
@hsluoyz this plugin has been on the market for some time now. It supports the latest two major versions: 201 and 202. Would it be possible to put a page on the Casbin website noting this plugin?

**Comment by hsluoyz** [comment]
@will7200 great work! Will do it definitely. Can you provide me a web page link to that plugin?

**Comment by will7200** [comment]
@hsluoyz yeah!the jetbrains link to is: https://plugins.jetbrains.com/plugin/14809-casbin

**Comment by hsluoyz** [comment]
@will7200 already added: 
![image](https://user-images.githubusercontent.com/3787410/92403075-4f236f00-f163-11ea-96eb-db3b7e8f25c6.png)

You can also send a PR to: https://github.com/casbin/casbin-website to add a detailed page for it. I want the users to know it more :)
