### ISSUE TITLE
目前最新版Casbin 0.1.11插件不支持GoLand 2023.1.1，DataGrip 2023.1.1了

### ISSUE THREAD

**Issue by lihaoqiang001** [will7200/casbin-idea-plugin#10]
https://plugins.jetbrains.com/plugin/14809-casbin

**Comment by hsluoyz** [comment]
@lihaoqiang001 plz modify your text into English

**Comment by hsluoyz** [comment]
Done at: https://github.com/will7200/casbin-idea-plugin/releases/tag/v0.1.12

**Comment by hsluoyz** [comment]
@will7200 hi, can you give me permission to modify issue title?

**Comment by will7200** [comment]
Hi @hsluoyz, invited you as collaborator. Thanks for helping out

**Comment by hsluoyz** [comment]
@will7200 thanks
