### ISSUE TITLE
casbin example prompts an error

### ISSUE THREAD

**Issue by c-myth** [will7200/casbin-idea-plugin#5]
casbin plugin version: `0.1.3`
jcasbin version: `1.7.1-SNAPSHOT`

[https://github.com/casbin/jcasbin/blob/master/examples/abac_model.conf](https://github.com/casbin/jcasbin/blob/master/examples/abac_model.conf)

The following content indicates an error
- `obj.`:  '&&' or '||' expected, got '.'
- `owner`: '=' expected

```conf
[matchers]
m = r.sub == r.obj.owner
```

**Comment by hsluoyz** [comment]
@will7200

**Comment by will7200** [comment]
The current parser doesn't account for attributes that are objects currently. I will update to allow sub models.

**Comment by will7200** [comment]
submitted to Jetbrains for approval
