### ISSUE TITLE
Incompatible with IEDA latest version 2021.2(IU-212)

### ISSUE THREAD

**Issue by tangyang9464** [will7200/casbin-idea-plugin#6]
![X1`)G5VGNZ2@V2OT)JQ6N}Q](https://user-images.githubusercontent.com/45587763/127424234-3169dac9-fc42-4b1b-8137-c02c83ac8e9b.jpg)

![8F@@ZQR{AV3`_LXMLZKLI8W](https://user-images.githubusercontent.com/45587763/127424261-762051c7-f062-4e67-b633-eacd0485a3ba.jpg)

@will7200

**Comment by will7200** [comment]
Pushed out b4b0b1bffab40fb60e2b7961708edcbec9bc1201 to jetbrains should be approved within a couple days.

**Comment by will7200** [comment]
its on the market now
