### ISSUE TITLE
'in' operator prompts an error

### ISSUE THREAD

**Issue by timconinx** [will7200/casbin-idea-plugin#7]
When trying the example on https://github.com/casbin/casbin/blob/277c1a2b85698272f764d71a94d2595a8d425915/examples/rbac_model_matcher_using_in_op.conf 
Matcher code like
```m = r.obj in (p.sub)```
gives an error on the space between `in` and `(`

**Comment by hsluoyz** [comment]
@will7200

**Comment by will7200** [comment]
I'll take a look at it. Thank you for bringing this up!

**Comment by will7200** [comment]
Pushed out a new version that updates the language syntax. Its available for download now.

**Comment by will7200** [comment]
Fixed in 5716b780f3bc050c323eeed351767c81947e3b80
